[project]
name = "analysis-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.2",
    "pyright>=1.1.407",
    "ruff>=0.14.10",
]

[tool.pyright]
include = [
    "src/**.py"
]
